version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: marketai-postgres
    environment:
      POSTGRES_DB: marketai
      POSTGRES_USER: marketai
      POSTGRES_PASSWORD: marketai123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - marketai-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: marketai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketai-network

  # API Server
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    container_name: marketai-api
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://marketai:marketai123@postgres:5432/marketai
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_here
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../../apps/api:/app
      - /app/node_modules
    networks:
      - marketai-network

  # Web App
  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: marketai-web
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - marketai-network

volumes:
  postgres_data:
  redis_data:

networks:
  marketai-network:
    driver: bridge
